// ─────────────────────────────────────────
//  Projects — add, remove, or edit entries
//  here to update the projects page.
// ─────────────────────────────────────────

export const projects = [
  {
    name: "Portfolio",
    icon: "🖥️",
    dir: "portfolio/",
    description: "This terminal-style developer portfolio with an interactive command-line interface",
    stack: ["Next.js", "React", "JavaScript", "CSS", "Vercel", "Github API", "Open-Meteo"],
    category: "personal",
    github: "github.com/endodod/Portfolio",
    githubUrl: "https://github.com/endodod/Portfolio",
    live: "paulkuehn.ch",
    liveUrl: "https://paulkuehn.ch",
    label: "live",
  },
  {
    name: "PortfolioAnalyzer",
    icon: "📈",
    dir: "portfolio-analyzer/",
    description: "Web app for analyzing security portfolios with real-time stock data",
    stack: ["Python", "Flask", "MySQL", "Pandas", "Docker", "Bootstrap 5", "yfinance"],
    category: "personal",
    github: "github.com/endodod/PortfolioAnalyzer",
    githubUrl: "https://github.com/endodod/PortfolioAnalyzer",
    label: "self host",
  },
  {
    name: "Floored",
    icon: "🎰",
    dir: "floored/",
    description: "Browser-based roguelike casino game: survive escalating floors across eightteen casino games",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL", "Neon", "Zustand", "Framer Motion", "PixiJS", "Vercel"],
    category: "personal",
    github: "github.com/endodod/Floored",
    githubUrl: "https://github.com/endodod/Floored",
    live: "floored.paulkuehn.ch",
    liveUrl: "https://floored.paulkuehn.ch/",
    label: "live",
  },
  {
    name: "BlackJack",
    icon: "🃏",
    dir: "blackjack/",
    description: "Browser-based blackjack site with multiplayer support",
    stack: ["Next.js", "React", "JavaScript", "CSS", "Vercel", "Prisma", "PostgreSQL", "Neon", "NextAuth.js", "PartyKit"],
    category: "personal",
    github: "github.com/endodod/BlackJack",
    githubUrl: "https://github.com/endodod/BlackJack",
    live: "blackjack.paulkuehn.ch",
    liveUrl: "https://blackjack.paulkuehn.ch",
    label: "live",
  },
  {
    name: "IMSGrades",
    icon: "📊",
    dir: "imsgrades/",
    description: "Web-based grade management system for Swiss vocational school students",
    stack: ["Python", "Flask", "JavaScript", "Bootstrap 5", "MySQL"],
    category: "hackathon",
    github: "github.com/im24a-kuehnp/IMSGrades",
    githubUrl: "https://github.com/im24a-kuehnp/IMSGrades",
    label: "prototype",
  },
  {
    name: "Trackworks",
    icon: "🏎️",
    dir: "trackworks/",
    description: "Online multiplayer party racing game where players build the track together, then race what they built",
    stack: ["Phaser 3", "React", "TypeScript", "Colyseus", "Zustand", "Vite", "Express"],
    category: "hackathon",
    github: "github.com/im24a-mendolag/trackworks",
    githubUrl: "https://github.com/im24a-mendolag/trackworks",
    label: "prototype",
  },
  {
    name: "Shelfle",
    icon: "🎮",
    dir: "shelfle/",
    description: "Steam-powered game guessing app with multiple gameplay modes",
    stack: ["Next.js", "React", "TypeScript", "Prisma", "PostgreSQL", "NextAuth.js"],
    category: "school",
    github: "github.com/im24a-mendolag/shelfle",
    githubUrl: "https://github.com/im24a-mendolag/shelfle",
  },
  {
    name: "URLShortener",
    icon: "🔗",
    dir: "urlshortner/",
    description: "Full-stack URL shortener with click tracking and an analytics dashboard",
    stack: ["Java", "Spring Boot", "React", "TypeScript", "Vite", "Docker"],
    category: "school",
    github: "github.com/im24a-mendolag/urlshortner",
    githubUrl: "https://github.com/im24a-mendolag/urlshortner",
  },
  {
    name: "WikiGhost",
    icon: "👻",
    dir: "wikighost/",
    description: "Fast reference and elimination tool for horror/investigation games",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    category: "personal",
    github: "github.com/endodod/WikiGhost",
    githubUrl: "https://github.com/endodod/WikiGhost",
    live: "wikighost.paulkuehn.ch",
    liveUrl: "https://wikighost.paulkuehn.ch",
    label: "live",
  },
  {
    name: "Geeked",
    icon: "🎲",
    dir: "geeked/",
    description: "Static reporting site presenting bot-simulation findings for board game strategies",
    stack: ["React", "TypeScript", "Vite", "React Router"],
    github: "github.com/endodod/geeked",
    githubUrl: "https://github.com/endodod/geeked",
    live: "coming soon",
    label: "coming soon",
  },
  {
    name: "SAP",
    icon: "🐾",
    dir: "sap/",
    description: "EOE reinforcement learning system for Super Auto Pets",
    stack: ["Python", "PyTorch", "Stable-Baselines3", "Gymnasium", "Next.js", "TypeScript", "Tailwind CSS", "Recharts", "D3.js", "Vercel"],
    category: "personal",
    label: "self host",
    repos: [
      { label: "sim", github: "github.com/endodod/sap-sim", githubUrl: "https://github.com/endodod/sap-sim" },
      { label: "agent", github: "github.com/endodod/sap-agent", githubUrl: "https://github.com/endodod/sap-agent" },
      { label: "dashboard", github: "github.com/endodod/sap-dashboard", githubUrl: "https://github.com/endodod/sap-dashboard" },
    ],
  },
  {
    name: "VectorRace",
    icon: "↗",
    dir: "vectorrace/",
    description: "Grid-based vector race editor and shortest-path solver",
    stack: ["React", "TypeScript", "Vite", "Python", "FastAPI"],
    github: "github.com/endodod/vectorrace",
    githubUrl: "https://github.com/endodod/vectorrace",
    label: "self host",
  },
  {
    name: "MyDailies",
    icon: "🔥",
    dir: "mydailies/",
    description: "Streak tracker for daily puzzles such as Wordle",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL"],
    github: "github.com/endodod/MyDailies",
    githubUrl: "https://github.com/endodod/MyDailies",
    label: "coming soon",
  },];
