// ─────────────────────────────────────────
//  Projects — add, remove, or edit entries
//  here to update the projects page.
// ─────────────────────────────────────────

export const projects = [
  {
    name: "Portfolio",
    icon: "🖥️",
    dir: "portfolio/",
    description: "Terminal-style developer portfolio with an interactive bash console — navigate pages via commands, browse projects, and view live git activity",
    stack: ["Next.js", "React", "JavaScript", "CSS", "Vercel", "Github API", "Open-Meteo"],
    github: "github.com/endodod/Portfolio",
    githubUrl: "https://github.com/endodod/Portfolio",
    live: "paulkuehn.ch",
    liveUrl: "https://paulkuehn.ch",
  },
  {
    name: "PortfolioAnalyzer",
    icon: "📈",
    dir: "portfolio-analyzer/",
    description: "Web app for analyzing security portfolios with real-time stock data",
    stack: ["Python", "Flask", "MySQL", "Docker", "Bootstrap 5", "yfinance"],
    github: "github.com/endodod/PortfolioAnalyzer",
    githubUrl: "https://github.com/endodod/PortfolioAnalyzer",
  },
  {
    name: "Floored",
    icon: "🎰",
    dir: "floored/",
    description: "Browser-based roguelike casino game — survive escalating floors with rising minimum bets across eight casino games",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Supabase", "Prisma", "PostgreSQL", "Zustand", "Framer Motion", "PixiJS", "Vercel"],
    github: "github.com/endodod/Floored",
    githubUrl: "https://github.com/endodod/Floored",
    live: "floored.paulkuehn.ch",
    liveUrl: "https://floored.paulkuehn.ch/",
  },
  {
    name: "BlackJack",
    icon: "🃏",
    dir: "blackjack/",
    description: "Browser-based Blackjack card game with Multiplayer support",
    stack: ["Next.js", "React", "JavaScript", "CSS", "Vercel", "Prisma", "PostgreSQL"],
    github: "github.com/endodod/BlackJack",
    githubUrl: "https://github.com/endodod/BlackJack",
    live: "blackjack.paulkuehn.ch",
    liveUrl: "https://blackjack.paulkuehn.ch",
  },
  {
    name: "WikiGhost",
    icon: "👻",
    dir: "wikighost/",
    description: "Fast reference and elimination tool for horror/investigation games",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    github: "github.com/endodod/WikiGhost",
    githubUrl: "https://github.com/endodod/WikiGhost",
    live: "wikighost.paulkuehn.ch",
    liveUrl: "https://wikighost.paulkuehn.ch",
  },
  {
    name: "Geeked",
    icon: "🎲",
    dir: "geeked/",
    description: "Static reporting site presenting bot-simulation findings for card game strategies",
    stack: ["React", "TypeScript", "Vite", "React Router"],
    github: "github.com/endodod/geeked",
    githubUrl: "https://github.com/endodod/geeked",
    live: "coming soon",
  },
  {
    name: "SAP",
    icon: "🐾",
    dir: "sap/",
    description: "End-to-end reinforcement learning system for Super Auto Pets — terminal game simulation, PPO-trained agent, and public dashboard visualizing learned pet strategies and win-rates",
    stack: ["Python", "PyTorch", "Stable-Baselines3", "Next.js", "TypeScript", "Vercel"],
    live: "coming soon",
    repos: [
      { label: "sim", github: "github.com/endodod/sap-sim", githubUrl: "https://github.com/endodod/sap-sim" },
      { label: "agent", github: "github.com/endodod/sap-agent", githubUrl: "https://github.com/endodod/sap-agent" },
      { label: "dashboard", github: "github.com/endodod/sap-dashboard", githubUrl: "https://github.com/endodod/sap-dashboard" },
    ],
  },
];
